/**
 * RMTC — Rimal Membrane Technologies, Jeddah.
 *
 * The continuous-web site, and the one that carries the energy and power
 * quality story: MV/LV distribution, harmonics, power factor, capacitor banks,
 * the ISO 50001 / IPMVP energy baseline, cost allocation and sustainability.
 *
 * Two production lines feed each other. ML1 casts and dries the flat-sheet
 * membrane and is measured in m²; EL1 rolls that sheet into spiral-wound
 * elements and is measured in pieces.
 *
 *   CD-01  casting drum      8.0 m/min × 1.0 m   480 m²/h
 *   CT-01  coating station   8.0 m/min           480 m²/h
 *   DR-01  drying tunnel     7.2 m/min           432 m²/h   ← the constraint
 *   SL-01  slitter           9.0 m/min           540 m²/h
 *
 * The drying tunnel is the constraint because residence time cannot be
 * compressed without under-curing the film, which is exactly the sort of
 * constraint a scheduling screen has to respect rather than average away.
 *
 * The electrical estate is modelled as first-class assets so that power
 * quality has somewhere to attach: two transformers, four distribution boards
 * and two capacitor banks. PFC-2 is modelled as a failed bank — it measures no
 * capacitance and draws no current — because a demonstration that only ever
 * shows healthy equipment proves nothing about the diagnostics.
 */

import type { FactoryDef } from './types';

export const RMTC: FactoryDef = {
  code: 'RMTC',
  name: 'Rimal Membrane Technologies',
  nameAr: 'رمال لتقنيات الأغشية',
  city: 'Jeddah',
  cityAr: 'جدة',
  district: 'Industrial City Phase 3',
  districtAr: 'المدينة الصناعية المرحلة الثالثة',
  lat: 21.3617,
  lng: 39.2094,
  color: '#4C9BD6',
  glowColor: 'rgba(76,155,214,0.30)',
  timezone: 'Asia/Riyadh',
  displayUnit: 'PIECE',
  paradigm: 'CONTINUOUS_WEB',
  type: 'CONTINUOUS_PROCESS',
  extraCapabilities: ['SERIAL_GENEALOGY'],
  // ML1 is measured in m2 of web; EL1 in finished elements.
  unitFactors: { M2: 1, ROLL: 400, PIECE: 1, PALLET: 24 },
  tagline: 'Energy, power quality and sustainability on a continuous process',
  taglineAr: 'الطاقة وجودة القدرة والاستدامة على عملية مستمرة',
  showcases: ['L1_CONNECTIVITY', 'L2_MES', 'L3_SIMULATION', 'L4_AI', 'DX', 'EMERGING'],

  areas: [
    { code: 'A-CST', name: 'Casting & Coating', nameAr: 'الصبّ والطلاء', type: 'MAKING' },
    { code: 'A-ASM', name: 'Element Assembly', nameAr: 'تجميع العناصر', type: 'PACKING' },
    { code: 'A-LAB', name: 'Membrane Laboratory', nameAr: 'مختبر الأغشية', type: 'LABORATORY' },
    { code: 'A-ELC', name: 'Electrical Distribution', nameAr: 'التوزيع الكهربائي', type: 'UTILITY' },
    { code: 'A-UTL', name: 'Utilities & Water Treatment', nameAr: 'المرافق ومعالجة المياه', type: 'UTILITY' },
    { code: 'A-WHS', name: 'Warehouse', nameAr: 'المستودع', type: 'WAREHOUSE' },
  ],

  lines: [
    { code: 'ML1', name: 'Membrane Casting Line', nameAr: 'خط صبّ الأغشية',
      type: 'MAKING', areaCode: 'A-CST', sortOrder: 1,
      oeeMethod: 'BOTTLENECK', bottleneckMachine: 'DR-01', outfeedMachines: ['SL-01'] },
    { code: 'EL1', name: 'Element Assembly Line', nameAr: 'خط تجميع العناصر',
      type: 'PACKING', areaCode: 'A-ASM', sortOrder: 2,
      oeeMethod: 'BOTTLENECK', bottleneckMachine: 'RL-01', outfeedMachines: ['TT-01'] },
  ],

  machines: [
    // ── ML1 casting ──────────────────────────────────────────────────────
    { code: 'CD-01', name: 'Casting Drum', nameAr: 'أسطوانة الصبّ',
      type: 'MACHINE', areaCode: 'A-CST', lineCode: 'ML1', sortOrder: 1,
      manufacturer: 'Coatema', model: 'Basecoater-1400', criticality: 'CRITICAL',
      designCapacity: 480, idealCycleSeconds: 7.5, countUnit: 'M2',
      downtimeThreshold: 60, installDate: '2021-08-19',
      metadata: { webWidthM: 1.0, lineSpeedMPerMin: 8.0 } },
    { code: 'CT-01', name: 'Coating Station', nameAr: 'محطة الطلاء',
      type: 'MACHINE', areaCode: 'A-CST', lineCode: 'ML1', sortOrder: 2,
      manufacturer: 'Coatema', model: 'Slot-Die-1400', criticality: 'CRITICAL',
      designCapacity: 480, idealCycleSeconds: 7.5, countUnit: 'M2',
      downtimeThreshold: 60, installDate: '2021-08-19' },
    { code: 'DR-01', name: 'Drying Tunnel', nameAr: 'نفق التجفيف',
      type: 'MACHINE', areaCode: 'A-CST', lineCode: 'ML1', sortOrder: 3,
      manufacturer: 'Krönert', model: 'DT-24', criticality: 'CRITICAL',
      designCapacity: 432, idealCycleSeconds: 8.33, countUnit: 'M2',
      downtimeThreshold: 90, installDate: '2021-08-19',
      metadata: { zones: 6, note: 'Line constraint — residence time is fixed by cure chemistry' } },
    { code: 'SL-01', name: 'Slitter & Rewinder', nameAr: 'ماكينة التقطيع واللف',
      type: 'MACHINE', areaCode: 'A-CST', lineCode: 'ML1', sortOrder: 4,
      manufacturer: 'Kampf', model: 'ConSlit', criticality: 'HIGH',
      designCapacity: 540, idealCycleSeconds: 6.67, countUnit: 'M2',
      downtimeThreshold: 60, installDate: '2021-10-04' },

    // ── EL1 element assembly ─────────────────────────────────────────────
    { code: 'RL-01', name: 'Element Rolling Machine', nameAr: 'ماكينة لف العناصر',
      type: 'MACHINE', areaCode: 'A-ASM', lineCode: 'EL1', sortOrder: 1,
      manufacturer: 'Sartorius', model: 'SW-8040', criticality: 'CRITICAL',
      designCapacity: 15, idealCycleSeconds: 240.0, countUnit: 'PIECE',
      downtimeThreshold: 90, installDate: '2021-11-22',
      metadata: { note: 'EL1 constraint' } },
    { code: 'GL-01', name: 'Glue Application Station', nameAr: 'محطة اللصق',
      type: 'MACHINE', areaCode: 'A-ASM', lineCode: 'EL1', sortOrder: 2,
      manufacturer: 'Nordson', model: 'ProBlue-15', criticality: 'HIGH',
      designCapacity: 20, idealCycleSeconds: 180.0, countUnit: 'PIECE',
      downtimeThreshold: 60, installDate: '2021-11-22' },
    { code: 'TT-01', name: 'Element Pressure Test', nameAr: 'اختبار ضغط العنصر',
      type: 'MACHINE', areaCode: 'A-ASM', lineCode: 'EL1', sortOrder: 3,
      manufacturer: 'Sartorius', model: 'PT-600', criticality: 'HIGH',
      designCapacity: 18, idealCycleSeconds: 200.0, countUnit: 'PIECE',
      downtimeThreshold: 60, installDate: '2021-11-22' },

    // ── Electrical distribution — the EMS estate ─────────────────────────
    { code: 'TR-01', name: 'Transformer TR-01 (13.8 kV / 400 V)', nameAr: 'المحوّل ١',
      type: 'TRANSFORMER', areaCode: 'A-ELC', sortOrder: 1,
      manufacturer: 'Schneider', model: 'Trihal-2500', criticality: 'CRITICAL',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { ratingKva: 2500, primaryKv: 13.8, secondaryV: 400, impedancePct: 6.0 } },
    { code: 'TR-02', name: 'Transformer TR-02 (13.8 kV / 400 V)', nameAr: 'المحوّل ٢',
      type: 'TRANSFORMER', areaCode: 'A-ELC', sortOrder: 2,
      manufacturer: 'Schneider', model: 'Trihal-2000', criticality: 'CRITICAL',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { ratingKva: 2000, primaryKv: 13.8, secondaryV: 400, impedancePct: 6.0 } },
    { code: 'MDP-1', name: 'Main Distribution Board 1', nameAr: 'لوحة التوزيع الرئيسية ١',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 3,
      manufacturer: 'Schneider', model: 'Blokset', criticality: 'CRITICAL',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { breakerAt: 2500, feeds: 'Casting & coating, drying tunnel', note: 'Highest distortion board' } },
    { code: 'MDP-2', name: 'Main Distribution Board 2', nameAr: 'لوحة التوزيع الرئيسية ٢',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 4,
      manufacturer: 'Schneider', model: 'Blokset', criticality: 'CRITICAL',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { breakerAt: 2500, feeds: 'Element assembly, laboratory' } },
    { code: 'MDP-3', name: 'Main Distribution Board 3', nameAr: 'لوحة التوزيع الرئيسية ٣',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 5,
      manufacturer: 'Schneider', model: 'Blokset', criticality: 'HIGH',
      downtimeThreshold: 300, installDate: '2023-02-14',
      metadata: { breakerAt: 1600, feeds: 'Utilities, chillers' } },
    { code: 'MDP-4', name: 'Main Distribution Board 4', nameAr: 'لوحة التوزيع الرئيسية ٤',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 6,
      manufacturer: 'Schneider', model: 'Blokset', criticality: 'HIGH',
      downtimeThreshold: 300, installDate: '2023-02-14',
      metadata: { breakerAt: 1600, feeds: 'Water treatment, warehouse' } },
    { code: 'PFC-1', name: 'Capacitor Bank PFC-1', nameAr: 'بنك المكثّفات ١',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 7,
      manufacturer: 'ABB', model: 'CLMD-250', criticality: 'HIGH',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { ratedKvar: 250, steps: 6, detunedReactor: false,
                  condition: 'Overloaded — draws above nameplate current with no detuning reactor' } },
    { code: 'PFC-2', name: 'Capacitor Bank PFC-2', nameAr: 'بنك المكثّفات ٢',
      type: 'MACHINE', areaCode: 'A-ELC', sortOrder: 8,
      manufacturer: 'ABB', model: 'CLMD-200', criticality: 'HIGH',
      downtimeThreshold: 300, installDate: '2021-05-30',
      metadata: { ratedKvar: 200, steps: 5, detunedReactor: false,
                  condition: 'Failed — measures no capacitance and draws no current' } },

    // ── Utilities ────────────────────────────────────────────────────────
    { code: 'CH-01', name: 'Chiller 1', nameAr: 'المبرّد ١',
      type: 'CHILLER', areaCode: 'A-UTL', sortOrder: 1,
      manufacturer: 'York', model: 'YVAA-0557', criticality: 'CRITICAL',
      downtimeThreshold: 180, installDate: '2021-06-15', metadata: { ratedKw: 420 } },
    { code: 'CH-02', name: 'Chiller 2', nameAr: 'المبرّد ٢',
      type: 'CHILLER', areaCode: 'A-UTL', sortOrder: 2,
      manufacturer: 'York', model: 'YVAA-0557', criticality: 'CRITICAL',
      downtimeThreshold: 180, installDate: '2021-06-15', metadata: { ratedKw: 420 } },
    { code: 'AC-01', name: 'Air Compressor', nameAr: 'ضاغط الهواء',
      type: 'COMPRESSOR', areaCode: 'A-UTL', sortOrder: 3,
      manufacturer: 'Ingersoll Rand', model: 'R-160i', criticality: 'HIGH',
      downtimeThreshold: 120, installDate: '2021-06-15', metadata: { ratedKw: 160 } },
    { code: 'PU-01', name: 'RO Feed Pump', nameAr: 'مضخّة التغذية',
      type: 'PUMP', areaCode: 'A-UTL', sortOrder: 4,
      manufacturer: 'Grundfos', model: 'CR-155', criticality: 'HIGH',
      downtimeThreshold: 120, installDate: '2021-06-15', metadata: { ratedKw: 55 } },
  ],

  shifts: [
    { code: 'A', name: 'Shift A — Day', nameAr: 'وردية أ — نهارية',
      startTime: '06:00', endTime: '18:00', crossesMidnight: false,
      shiftDurationHours: 12, plannedProductionHours: 11.0,
      breakMinutes: 45, cleaningMinutes: 15, days: [0, 1, 2, 3, 4, 5],
      targetQtyPerShift: 4400, targetUnit: 'M2', efficiencyFactor: 1.0 },
    { code: 'B', name: 'Shift B — Night', nameAr: 'وردية ب — ليلية',
      startTime: '18:00', endTime: '06:00', crossesMidnight: true,
      shiftDurationHours: 12, plannedProductionHours: 10.75,
      breakMinutes: 45, cleaningMinutes: 30, days: [0, 1, 2, 3, 4, 5],
      targetQtyPerShift: 4050, targetUnit: 'M2', efficiencyFactor: 0.93 },
  ],

  downtimeCauses: [
    { code: 'L1-PROC', name: 'Process', nameAr: 'العملية', category: 'PROCESS', isPlanned: false, level: 1 },
    { code: 'L2-WEB', name: 'Web handling', nameAr: 'مناولة الشريط', category: 'PROCESS', isPlanned: false, level: 2, parent: 'L1-PROC' },
    { code: 'PROC-WEB-BREAK', name: 'Web break', nameAr: 'قطع الشريط', category: 'PROCESS', isPlanned: false, level: 3, parent: 'L2-WEB', weight: 25, durationRange: [12, 55] },
    { code: 'PROC-TENSION', name: 'Tension control deviation', nameAr: 'انحراف التحكم بالشدّ', category: 'PROCESS', isPlanned: false, level: 3, parent: 'L2-WEB', weight: 11, durationRange: [5, 20] },
    { code: 'L2-COAT', name: 'Coating', nameAr: 'الطلاء', category: 'PROCESS', isPlanned: false, level: 2, parent: 'L1-PROC' },
    { code: 'PROC-STREAK', name: 'Coating streak', nameAr: 'خطوط في الطلاء', category: 'PROCESS', isPlanned: false, level: 3, parent: 'L2-COAT', weight: 14, durationRange: [10, 40] },
    { code: 'PROC-DIE-CLEAN', name: 'Slot die cleaning', nameAr: 'تنظيف فوهة الطلاء', category: 'PROCESS', isPlanned: false, level: 3, parent: 'L2-COAT', weight: 9, durationRange: [20, 60] },
    { code: 'L2-DRY', name: 'Drying', nameAr: 'التجفيف', category: 'PROCESS', isPlanned: false, level: 2, parent: 'L1-PROC' },
    { code: 'PROC-DRY-TEMP', name: 'Drying zone temperature deviation', nameAr: 'انحراف حرارة منطقة التجفيف', category: 'PROCESS', isPlanned: false, level: 3, parent: 'L2-DRY', weight: 8, durationRange: [15, 45] },

    { code: 'L1-UTL', name: 'Utility', nameAr: 'المرافق', category: 'UTILITY', isPlanned: false, level: 1 },
    { code: 'L2-PQ', name: 'Power quality', nameAr: 'جودة القدرة', category: 'UTILITY', isPlanned: false, level: 2, parent: 'L1-UTL' },
    { code: 'UTL-VSAG', name: 'Voltage sag trip', nameAr: 'فصل بسبب هبوط الجهد', category: 'UTILITY', isPlanned: false, level: 3, parent: 'L2-PQ', weight: 12, durationRange: [8, 35] },
    { code: 'UTL-VDIP-RECOVER', name: 'Restart after voltage dip', nameAr: 'إعادة تشغيل بعد انخفاض الجهد', category: 'UTILITY', isPlanned: false, level: 3, parent: 'L2-PQ', weight: 7, durationRange: [5, 20] },
    { code: 'L2-CHW', name: 'Chilled water', nameAr: 'الماء المبرّد', category: 'UTILITY', isPlanned: false, level: 2, parent: 'L1-UTL' },
    { code: 'UTL-CHW-TEMP', name: 'Chilled water temperature high', nameAr: 'ارتفاع حرارة الماء المبرّد', category: 'UTILITY', isPlanned: false, level: 3, parent: 'L2-CHW', weight: 6, durationRange: [15, 50] },

    { code: 'L1-MECH', name: 'Mechanical', nameAr: 'ميكانيكي', category: 'MECHANICAL', isPlanned: false, level: 1 },
    { code: 'L2-ROLL', name: 'Rolls & drives', nameAr: 'الأسطوانات والمشغّلات', category: 'MECHANICAL', isPlanned: false, level: 2, parent: 'L1-MECH' },
    { code: 'MECH-ROLL-CLEAN', name: 'Roll cleaning', nameAr: 'تنظيف الأسطوانات', category: 'MECHANICAL', isPlanned: false, level: 3, parent: 'L2-ROLL', weight: 10, durationRange: [15, 35] },
    { code: 'MECH-BEARING', name: 'Bearing replacement', nameAr: 'استبدال محمل', category: 'MECHANICAL', isPlanned: false, level: 3, parent: 'L2-ROLL', weight: 4, durationRange: [60, 210] },

    { code: 'L1-MAT', name: 'Material', nameAr: 'مواد', category: 'MATERIAL', isPlanned: false, level: 1 },
    { code: 'L2-RSUP', name: 'Supply', nameAr: 'التوريد', category: 'MATERIAL', isPlanned: false, level: 2, parent: 'L1-MAT' },
    { code: 'MAT-SUBSTRATE', name: 'Substrate roll change', nameAr: 'تغيير بكرة الحامل', category: 'MATERIAL', isPlanned: false, level: 3, parent: 'L2-RSUP', weight: 13, durationRange: [10, 25] },
    { code: 'MAT-DOPE', name: 'Casting dope starved', nameAr: 'نفاد محلول الصبّ', category: 'MATERIAL', isPlanned: false, level: 3, parent: 'L2-RSUP', weight: 6, durationRange: [20, 60] },

    { code: 'L1-QUA', name: 'Quality', nameAr: 'الجودة', category: 'QUALITY', isPlanned: false, level: 1 },
    { code: 'L2-QH', name: 'Quality hold', nameAr: 'إيقاف للجودة', category: 'QUALITY', isPlanned: false, level: 2, parent: 'L1-QUA' },
    { code: 'QUA-FLUX', name: 'Flux out of specification', nameAr: 'التدفّق خارج المواصفة', category: 'QUALITY', isPlanned: false, level: 3, parent: 'L2-QH', weight: 8, durationRange: [20, 70] },
    { code: 'QUA-REJECT', name: 'Salt rejection below limit', nameAr: 'رفض الأملاح تحت الحد', category: 'QUALITY', isPlanned: false, level: 3, parent: 'L2-QH', weight: 6, durationRange: [25, 80] },

    { code: 'L1-CHG', name: 'Changeover', nameAr: 'تغيير الإنتاج', category: 'CHANGEOVER', isPlanned: true, level: 1 },
    { code: 'L2-GRADE', name: 'Grade change', nameAr: 'تغيير الرتبة', category: 'CHANGEOVER', isPlanned: true, level: 2, parent: 'L1-CHG' },
    { code: 'CHG-GRADE', name: 'Membrane grade changeover', nameAr: 'تغيير رتبة الغشاء', category: 'CHANGEOVER', isPlanned: true, level: 3, parent: 'L2-GRADE', weight: 7, durationRange: [40, 110] },
    { code: 'CHG-WIDTH', name: 'Slitting width change', nameAr: 'تغيير عرض التقطيع', category: 'CHANGEOVER', isPlanned: true, level: 3, parent: 'L2-GRADE', weight: 5, durationRange: [20, 50] },
    { code: 'CHG-ELEM', name: 'Element size changeover', nameAr: 'تغيير مقاس العنصر', category: 'CHANGEOVER', isPlanned: true, level: 3, parent: 'L2-GRADE', weight: 4, durationRange: [30, 80] },

    { code: 'L1-PLN', name: 'Planned', nameAr: 'مخطط', category: 'PLANNED_MAINTENANCE', isPlanned: true, level: 1 },
    { code: 'L2-RPM', name: 'Preventive maintenance', nameAr: 'صيانة وقائية', category: 'PLANNED_MAINTENANCE', isPlanned: true, level: 2, parent: 'L1-PLN' },
    { code: 'PLN-PM', name: 'Scheduled PM window', nameAr: 'نافذة صيانة مجدولة', category: 'PLANNED_MAINTENANCE', isPlanned: true, level: 3, parent: 'L2-RPM', weight: 5, durationRange: [90, 240] },
    { code: 'L2-RCLN', name: 'Cleaning', nameAr: 'تنظيف', category: 'PLANNED_CLEANING', isPlanned: true, level: 2, parent: 'L1-PLN' },
    { code: 'PLN-CLEAN', name: 'Line cleaning', nameAr: 'تنظيف الخط', category: 'PLANNED_CLEANING', isPlanned: true, level: 3, parent: 'L2-RCLN', weight: 6, durationRange: [30, 75] },
    { code: 'L2-RBRK', name: 'Breaks', nameAr: 'استراحات', category: 'PLANNED_BREAK', isPlanned: true, level: 2, parent: 'L1-PLN' },
    { code: 'PLN-BREAK', name: 'Operator break', nameAr: 'استراحة المشغّل', category: 'PLANNED_BREAK', isPlanned: true, level: 3, parent: 'L2-RBRK', weight: 8, durationRange: [15, 45] },
  ],

  products: [
    { code: 'RMT-BW8040', name: 'Brackish Water Element 8040', nameAr: 'عنصر مياه قليلة الملوحة ٨٠٤٠',
      category: 'RO Element', brand: 'Rimal BW', baseUnit: 'PIECE',
      packagingLadder: [{ unit: 'PIECE', perParent: 1 }, { unit: 'PALLET', perParent: 24 }], isActive: true },
    { code: 'RMT-SW8040', name: 'Seawater Element 8040', nameAr: 'عنصر مياه بحر ٨٠٤٠',
      category: 'RO Element', brand: 'Rimal SW', baseUnit: 'PIECE',
      packagingLadder: [{ unit: 'PIECE', perParent: 1 }, { unit: 'PALLET', perParent: 24 }], isActive: true },
    { code: 'RMT-NF4040', name: 'Nanofiltration Element 4040', nameAr: 'عنصر ترشيح نانوي ٤٠٤٠',
      category: 'NF Element', brand: 'Rimal NF', baseUnit: 'PIECE',
      packagingLadder: [{ unit: 'PIECE', perParent: 1 }, { unit: 'PALLET', perParent: 60 }], isActive: true },
    { code: 'RMT-SHEET', name: 'Flat Sheet Membrane', nameAr: 'غشاء مسطّح',
      category: 'Flat Sheet', brand: 'Rimal', baseUnit: 'M2',
      packagingLadder: [{ unit: 'M2', perParent: 1 }, { unit: 'ROLL', perParent: 400 }], isActive: true },
  ],

  materials: [
    { code: 'RM-PSF', name: 'Polysulfone Resin', nameAr: 'راتنج البولي سلفون', type: 'RAW', unit: 'KG', criticalStock: 3000 },
    { code: 'RM-NMP', name: 'NMP Solvent', nameAr: 'مذيب NMP', type: 'RAW', unit: 'L', shelfLifeDays: 730, criticalStock: 4000 },
    { code: 'RM-MPD', name: 'M-Phenylenediamine', nameAr: 'مادة MPD', type: 'RAW', unit: 'KG', shelfLifeDays: 365, criticalStock: 500 },
    { code: 'RM-TMC', name: 'Trimesoyl Chloride', nameAr: 'مادة TMC', type: 'RAW', unit: 'KG', shelfLifeDays: 365, criticalStock: 350 },
    { code: 'RM-SUB', name: 'Polyester Substrate Roll', nameAr: 'بكرة حامل بوليستر', type: 'RAW', unit: 'ROLL', criticalStock: 40 },
    { code: 'CP-PERM', name: 'Permeate Carrier Fabric', nameAr: 'قماش ناقل النفاذ', type: 'RAW', unit: 'M2', criticalStock: 8000 },
    { code: 'CP-FEED', name: 'Feed Spacer Mesh', nameAr: 'شبكة المباعد', type: 'RAW', unit: 'M2', criticalStock: 8000 },
    { code: 'CP-TUBE', name: 'Permeate Tube', nameAr: 'أنبوب النفاذ', type: 'RAW', unit: 'PCS', criticalStock: 900 },
    { code: 'CP-GLUE', name: 'Polyurethane Adhesive', nameAr: 'لاصق بولي يوريثان', type: 'RAW', unit: 'KG', shelfLifeDays: 180, criticalStock: 300 },
    { code: 'PK-WRAP', name: 'Fiberglass Outer Wrap', nameAr: 'غلاف ألياف زجاجية', type: 'PACKAGING', unit: 'M2', criticalStock: 2500 },
    { code: 'PK-BAG', name: 'Preservation Bag', nameAr: 'كيس حفظ', type: 'PACKAGING', unit: 'PCS', criticalStock: 1200 },
  ],

  routing: [
    { sequence: 1, code: 'RS-CAST', name: 'Membrane Casting', nameAr: 'صبّ الغشاء',
      machines: ['CD-01'], idealCycleSeconds: 7.5, consumes: ['RM-PSF', 'RM-NMP', 'RM-SUB'], tests: ['QS-THICK'] },
    { sequence: 2, code: 'RS-COAT', name: 'Interfacial Coating', nameAr: 'الطلاء البيني',
      machines: ['CT-01'], idealCycleSeconds: 7.5, consumes: ['RM-MPD', 'RM-TMC'], tests: ['QS-COATWT'] },
    { sequence: 3, code: 'RS-DRY', name: 'Drying & Curing', nameAr: 'التجفيف والمعالجة',
      machines: ['DR-01'], idealCycleSeconds: 8.33, tests: ['QS-DRYTEMP'] },
    { sequence: 4, code: 'RS-SLIT', name: 'Slitting & Rewinding', nameAr: 'التقطيع واللف',
      machines: ['SL-01'], idealCycleSeconds: 6.67, tests: ['QS-FLUX', 'QS-SALT'] },
    { sequence: 5, code: 'RS-ROLL', name: 'Element Rolling', nameAr: 'لف العنصر',
      machines: ['RL-01'], idealCycleSeconds: 240.0, consumes: ['CP-PERM', 'CP-FEED', 'CP-TUBE'] },
    { sequence: 6, code: 'RS-GLUE', name: 'Glue & Outer Wrap', nameAr: 'اللصق والتغليف',
      machines: ['GL-01'], idealCycleSeconds: 180.0, consumes: ['CP-GLUE', 'PK-WRAP'] },
    { sequence: 7, code: 'RS-TEST', name: 'Element Pressure Test', nameAr: 'اختبار ضغط العنصر',
      machines: ['TT-01'], idealCycleSeconds: 200.0, consumes: ['PK-BAG'], tests: ['QS-ELEMFLUX', 'QS-ELEMSALT'] },
  ],

  qualitySpecs: [
    { code: 'QS-THICK', name: 'Membrane thickness', nameAr: 'سماكة الغشاء', stepCode: 'RS-CAST',
      unit: 'µm', lsl: 118, usl: 132, target: 125, sampleRate: 0.10, baselinePassRate: 0.985 },
    { code: 'QS-COATWT', name: 'Coating weight', nameAr: 'وزن الطلاء', stepCode: 'RS-COAT',
      unit: 'g/m²', lsl: 0.14, usl: 0.22, target: 0.18, sampleRate: 0.10, baselinePassRate: 0.979 },
    { code: 'QS-DRYTEMP', name: 'Cure zone temperature', nameAr: 'حرارة منطقة المعالجة', stepCode: 'RS-DRY',
      unit: '°C', lsl: 92, usl: 104, target: 98, sampleRate: 1.0, baselinePassRate: 0.992 },
    { code: 'QS-FLUX', name: 'Sheet permeate flux', nameAr: 'تدفّق النفاذ للشريحة', stepCode: 'RS-SLIT',
      unit: 'L/m²·h', lsl: 32, target: 38, sampleRate: 0.05, baselinePassRate: 0.974 },
    { code: 'QS-SALT', name: 'Sheet salt rejection', nameAr: 'رفض الأملاح للشريحة', stepCode: 'RS-SLIT',
      unit: '%', lsl: 99.2, target: 99.6, sampleRate: 0.05, baselinePassRate: 0.981 },
    { code: 'QS-ELEMFLUX', name: 'Element flow rate', nameAr: 'معدّل تدفّق العنصر', stepCode: 'RS-TEST',
      unit: 'm³/d', lsl: 34, target: 41, sampleRate: 1.0, baselinePassRate: 0.977 },
    { code: 'QS-ELEMSALT', name: 'Element salt rejection', nameAr: 'رفض الأملاح للعنصر', stepCode: 'RS-TEST',
      unit: '%', lsl: 99.0, target: 99.5, sampleRate: 1.0, baselinePassRate: 0.983 },
  ],

  scrapCodes: [
    { code: 'SC-PINHOLE', name: 'Pinhole defect', nameAr: 'ثقب دقيق', stepCode: 'RS-COAT', weight: 24 },
    { code: 'SC-STREAK', name: 'Coating streak', nameAr: 'خط في الطلاء', stepCode: 'RS-COAT', weight: 19 },
    { code: 'SC-WEBBRK', name: 'Web break loss', nameAr: 'فاقد قطع الشريط', stepCode: 'RS-CAST', weight: 17 },
    { code: 'SC-THICK', name: 'Thickness out of tolerance', nameAr: 'سماكة خارج التفاوت', stepCode: 'RS-CAST', weight: 13 },
    { code: 'SC-UNDERCURE', name: 'Under-cured film', nameAr: 'معالجة ناقصة', stepCode: 'RS-DRY', weight: 11 },
    { code: 'SC-GLUE', name: 'Glue line failure', nameAr: 'فشل خط اللصق', stepCode: 'RS-GLUE', weight: 9 },
    { code: 'SC-ELEMFAIL', name: 'Element test failure', nameAr: 'فشل اختبار العنصر', stepCode: 'RS-TEST', weight: 7 },
  ],

  devices: [
    { code: 'PLC-RMTC-CAST', name: 'Casting Line PLC', protocol: 'MODBUS_TCP', port: 5041,
      unitId: 1, areaCode: 'A-CST', lineCode: 'ML1', pollMs: 200, tags: [
      { code: 'CD-01.STATUS', name: 'CD-01 Running', role: 'STATUS', ownerCode: 'CD-01', address: 0, dataType: 'BOOL', pollMs: 200 },
      { code: 'CD-01.TOTAL', name: 'CD-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'CD-01', address: 1, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'CD-01.GOOD', name: 'CD-01 Good', role: 'COUNTER_GOOD', ownerCode: 'CD-01', address: 2, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'CD-01.SPEED', name: 'CD-01 Line speed', role: 'PROCESS', ownerCode: 'CD-01', address: 400, dataType: 'FLOAT32', unit: 'm/min', pollMs: 1000, range: [0, 10] },
      { code: 'CD-01.TENSION', name: 'CD-01 Web tension', role: 'PROCESS', ownerCode: 'CD-01', address: 402, dataType: 'FLOAT32', unit: 'N', pollMs: 1000, range: [80, 160] },
      { code: 'CT-01.STATUS', name: 'CT-01 Running', role: 'STATUS', ownerCode: 'CT-01', address: 3, dataType: 'BOOL', pollMs: 200 },
      { code: 'CT-01.TOTAL', name: 'CT-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'CT-01', address: 4, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'CT-01.GOOD', name: 'CT-01 Good', role: 'COUNTER_GOOD', ownerCode: 'CT-01', address: 5, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'CT-01.COATWT', name: 'CT-01 Coating weight', role: 'PROCESS', ownerCode: 'CT-01', address: 404, dataType: 'FLOAT32', unit: 'g/m²', pollMs: 1000, range: [0.10, 0.26] },
      { code: 'DR-01.STATUS', name: 'DR-01 Running', role: 'STATUS', ownerCode: 'DR-01', address: 6, dataType: 'BOOL', pollMs: 200 },
      { code: 'DR-01.TOTAL', name: 'DR-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'DR-01', address: 7, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'DR-01.GOOD', name: 'DR-01 Good', role: 'COUNTER_GOOD', ownerCode: 'DR-01', address: 8, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'DR-01.ZONE3', name: 'DR-01 Cure zone temperature', role: 'PROCESS', ownerCode: 'DR-01', address: 406, dataType: 'FLOAT32', unit: '°C', pollMs: 1000, range: [85, 110] },
      { code: 'SL-01.STATUS', name: 'SL-01 Running', role: 'STATUS', ownerCode: 'SL-01', address: 9, dataType: 'BOOL', pollMs: 200 },
      { code: 'SL-01.TOTAL', name: 'SL-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'SL-01', address: 10, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
      { code: 'SL-01.GOOD', name: 'SL-01 Good', role: 'COUNTER_GOOD', ownerCode: 'SL-01', address: 11, dataType: 'BOOL', unit: 'M2', pollMs: 200 },
    ] },
    { code: 'PLC-RMTC-ASM', name: 'Element Assembly PLC', protocol: 'MODBUS_TCP', port: 5042,
      unitId: 1, areaCode: 'A-ASM', lineCode: 'EL1', pollMs: 200, tags: [
      { code: 'RL-01.STATUS', name: 'RL-01 Running', role: 'STATUS', ownerCode: 'RL-01', address: 0, dataType: 'BOOL', pollMs: 200 },
      { code: 'RL-01.TOTAL', name: 'RL-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'RL-01', address: 1, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'RL-01.GOOD', name: 'RL-01 Good', role: 'COUNTER_GOOD', ownerCode: 'RL-01', address: 2, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'GL-01.STATUS', name: 'GL-01 Running', role: 'STATUS', ownerCode: 'GL-01', address: 3, dataType: 'BOOL', pollMs: 200 },
      { code: 'GL-01.TOTAL', name: 'GL-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'GL-01', address: 4, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'GL-01.GOOD', name: 'GL-01 Good', role: 'COUNTER_GOOD', ownerCode: 'GL-01', address: 5, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'TT-01.STATUS', name: 'TT-01 Running', role: 'STATUS', ownerCode: 'TT-01', address: 6, dataType: 'BOOL', pollMs: 200 },
      { code: 'TT-01.TOTAL', name: 'TT-01 Total', role: 'COUNTER_TOTAL', ownerCode: 'TT-01', address: 7, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'TT-01.GOOD', name: 'TT-01 Good', role: 'COUNTER_GOOD', ownerCode: 'TT-01', address: 8, dataType: 'BOOL', unit: 'PIECE', pollMs: 200 },
      { code: 'TT-01.PRESSURE', name: 'TT-01 Test pressure', role: 'PROCESS', ownerCode: 'TT-01', address: 410, dataType: 'FLOAT32', unit: 'bar', pollMs: 1000, range: [0, 70] },
    ] },

    // ── Power quality meters. These carry the harmonics and PQ story, so they
    //    expose the full electrical tag set rather than just kW and kWh.
    { code: 'PQM-MDP1', name: 'Power Quality Meter — MDP-1', protocol: 'MODBUS_TCP', port: 5043,
      unitId: 1, areaCode: 'A-ELC', pollMs: 1000, tags: [
      { code: 'MDP-1.V', name: 'MDP-1 Voltage L-L', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3000, dataType: 'FLOAT32', unit: 'V', pollMs: 1000, range: [370, 415] },
      { code: 'MDP-1.A', name: 'MDP-1 Current', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3002, dataType: 'FLOAT32', unit: 'A', pollMs: 1000, range: [0, 1600] },
      { code: 'MDP-1.KW', name: 'MDP-1 Active power', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3004, dataType: 'FLOAT32', unit: 'kW', pollMs: 1000, range: [0, 1100] },
      { code: 'MDP-1.KVAR', name: 'MDP-1 Reactive power', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3006, dataType: 'FLOAT32', unit: 'kVAr', pollMs: 1000, range: [0, 600] },
      { code: 'MDP-1.PF', name: 'MDP-1 Power factor', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3008, dataType: 'FLOAT32', unit: '', pollMs: 1000, range: [0.78, 0.98] },
      { code: 'MDP-1.VTHD', name: 'MDP-1 Voltage THD', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3010, dataType: 'FLOAT32', unit: '%', pollMs: 1000, range: [2.0, 7.5] },
      { code: 'MDP-1.ITHD', name: 'MDP-1 Current THD', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3012, dataType: 'FLOAT32', unit: '%', pollMs: 1000, range: [6, 30] },
      { code: 'MDP-1.KWH', name: 'MDP-1 Energy total', role: 'ENERGY', ownerCode: 'EM-MDP1', address: 3014, dataType: 'FLOAT32', unit: 'kWh', pollMs: 5000 },
    ] },
    { code: 'PQM-MDP2', name: 'Power Quality Meter — MDP-2', protocol: 'MODBUS_TCP', port: 5044,
      unitId: 1, areaCode: 'A-ELC', pollMs: 1000, tags: [
      { code: 'MDP-2.V', name: 'MDP-2 Voltage L-L', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3000, dataType: 'FLOAT32', unit: 'V', pollMs: 1000, range: [380, 412] },
      { code: 'MDP-2.A', name: 'MDP-2 Current', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3002, dataType: 'FLOAT32', unit: 'A', pollMs: 1000, range: [0, 1000] },
      { code: 'MDP-2.KW', name: 'MDP-2 Active power', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3004, dataType: 'FLOAT32', unit: 'kW', pollMs: 1000, range: [0, 700] },
      { code: 'MDP-2.KVAR', name: 'MDP-2 Reactive power', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3006, dataType: 'FLOAT32', unit: 'kVAr', pollMs: 1000, range: [0, 320] },
      { code: 'MDP-2.PF', name: 'MDP-2 Power factor', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3008, dataType: 'FLOAT32', unit: '', pollMs: 1000, range: [0.86, 0.98] },
      { code: 'MDP-2.VTHD', name: 'MDP-2 Voltage THD', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3010, dataType: 'FLOAT32', unit: '%', pollMs: 1000, range: [1.5, 4.5] },
      { code: 'MDP-2.ITHD', name: 'MDP-2 Current THD', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3012, dataType: 'FLOAT32', unit: '%', pollMs: 1000, range: [4, 18] },
      { code: 'MDP-2.KWH', name: 'MDP-2 Energy total', role: 'ENERGY', ownerCode: 'EM-MDP2', address: 3014, dataType: 'FLOAT32', unit: 'kWh', pollMs: 5000 },
    ] },
    { code: 'PQM-UTL', name: 'Power Quality Meter — Utilities (MDP-3/4)', protocol: 'MODBUS_TCP', port: 5045,
      unitId: 1, areaCode: 'A-UTL', pollMs: 1000, tags: [
      { code: 'MDP-3.KW', name: 'MDP-3 Active power', role: 'ENERGY', ownerCode: 'EM-MDP3', address: 3004, dataType: 'FLOAT32', unit: 'kW', pollMs: 1000, range: [0, 900] },
      { code: 'MDP-3.PF', name: 'MDP-3 Power factor', role: 'ENERGY', ownerCode: 'EM-MDP3', address: 3008, dataType: 'FLOAT32', unit: '', pollMs: 1000, range: [0.82, 0.97] },
      { code: 'MDP-3.KWH', name: 'MDP-3 Energy total', role: 'ENERGY', ownerCode: 'EM-MDP3', address: 3014, dataType: 'FLOAT32', unit: 'kWh', pollMs: 5000 },
      { code: 'MDP-4.KW', name: 'MDP-4 Active power', role: 'ENERGY', ownerCode: 'EM-MDP4', address: 3020, dataType: 'FLOAT32', unit: 'kW', pollMs: 1000, range: [0, 500] },
      { code: 'MDP-4.PF', name: 'MDP-4 Power factor', role: 'ENERGY', ownerCode: 'EM-MDP4', address: 3024, dataType: 'FLOAT32', unit: '', pollMs: 1000, range: [0.84, 0.97] },
      { code: 'MDP-4.KWH', name: 'MDP-4 Energy total', role: 'ENERGY', ownerCode: 'EM-MDP4', address: 3030, dataType: 'FLOAT32', unit: 'kWh', pollMs: 5000 },
      { code: 'PFC-1.A', name: 'PFC-1 Bank current', role: 'ENERGY', ownerCode: 'PFC-1', address: 3040, dataType: 'FLOAT32', unit: 'A', pollMs: 5000, range: [0, 60] },
      { code: 'PFC-2.A', name: 'PFC-2 Bank current', role: 'ENERGY', ownerCode: 'PFC-2', address: 3042, dataType: 'FLOAT32', unit: 'A', pollMs: 5000, range: [0, 50] },
    ] },
  ],

  gateways: [
    { code: 'GW-RMTC-01', name: 'RMTC Edge Gateway — Production', location: 'Casting hall control room',
      devices: ['PLC-RMTC-CAST', 'PLC-RMTC-ASM'] },
    { code: 'GW-RMTC-02', name: 'RMTC Edge Gateway — Electrical Room', location: 'MV/LV substation',
      devices: ['PQM-MDP1', 'PQM-MDP2', 'PQM-UTL'] },
  ],

  energyMeters: [
    { code: 'EM-MDP1', meterNumber: 'RMTC-EM-001', name: 'MDP-1 — Casting & Drying', nameAr: 'لوحة ١ — الصبّ والتجفيف',
      type: 'ELECTRICAL', unit: 'kWh', machineCode: 'MDP-1', manufacturer: 'Schneider', model: 'PM8000', baselineKw: 742 },
    { code: 'EM-MDP2', meterNumber: 'RMTC-EM-002', name: 'MDP-2 — Assembly & Laboratory', nameAr: 'لوحة ٢ — التجميع والمختبر',
      type: 'ELECTRICAL', unit: 'kWh', machineCode: 'MDP-2', manufacturer: 'Schneider', model: 'PM8000', baselineKw: 468 },
    { code: 'EM-MDP3', meterNumber: 'RMTC-EM-003', name: 'MDP-3 — Utilities & Chillers', nameAr: 'لوحة ٣ — المرافق والمبرّدات',
      type: 'ELECTRICAL', unit: 'kWh', machineCode: 'MDP-3', manufacturer: 'Schneider', model: 'PM5560', baselineKw: 615 },
    { code: 'EM-MDP4', meterNumber: 'RMTC-EM-004', name: 'MDP-4 — Water Treatment & Warehouse', nameAr: 'لوحة ٤ — معالجة المياه والمستودع',
      type: 'ELECTRICAL', unit: 'kWh', machineCode: 'MDP-4', manufacturer: 'Schneider', model: 'PM5560', baselineKw: 288 },
    { code: 'EM-ML1', meterNumber: 'RMTC-EM-005', name: 'Membrane Casting Line', nameAr: 'خط صبّ الأغشية',
      type: 'ELECTRICAL', unit: 'kWh', lineCode: 'ML1', manufacturer: 'Schneider', model: 'PM5110', baselineKw: 405 },
    { code: 'EM-EL1', meterNumber: 'RMTC-EM-006', name: 'Element Assembly Line', nameAr: 'خط تجميع العناصر',
      type: 'ELECTRICAL', unit: 'kWh', lineCode: 'EL1', manufacturer: 'Schneider', model: 'PM5110', baselineKw: 132 },
    { code: 'CWM-01', meterNumber: 'RMTC-CW-001', name: 'Chilled Water', nameAr: 'الماء المبرّد',
      type: 'CHILLED_WATER', unit: 'm3', areaCode: 'A-UTL', manufacturer: 'Siemens', model: 'MAG-5100' },
    { code: 'WM-RO', meterNumber: 'RMTC-WM-001', name: 'RO Feed Water', nameAr: 'مياه التغذية',
      type: 'WATER', unit: 'm3', machineCode: 'PU-01', manufacturer: 'Itron', model: 'Woltex' },
  ],

  alarmRules: [
    { code: 'AL-MDP1-PF', name: 'MDP-1 power factor below 0.90', nameAr: 'معامل القدرة للوحة ١ تحت ٠٫٩٠',
      tagCode: 'MDP-1.PF', condition: 'LT', threshold: 0.90, severity: 'WARNING', delaySeconds: 300, hysteresis: 0.02 },
    { code: 'AL-MDP1-ITHD', name: 'MDP-1 current THD above IEEE 519 limit', nameAr: 'تشوّه التيار للوحة ١ فوق حد IEEE 519',
      tagCode: 'MDP-1.ITHD', condition: 'GT', threshold: 15, severity: 'CRITICAL', delaySeconds: 120, hysteresis: 1.5 },
    { code: 'AL-MDP1-VTHD', name: 'MDP-1 voltage THD above EN 50160 limit', nameAr: 'تشوّه الجهد للوحة ١ فوق حد EN 50160',
      tagCode: 'MDP-1.VTHD', condition: 'GT', threshold: 5.0, severity: 'WARNING', delaySeconds: 300, hysteresis: 0.3 },
    { code: 'AL-VSAG', name: 'Voltage sag below ride-through envelope', nameAr: 'هبوط الجهد تحت مغلّف التحمّل',
      tagCode: 'MDP-1.V', condition: 'LT', threshold: 360, severity: 'CRITICAL', delaySeconds: 1 },
    { code: 'AL-PFC1-OVER', name: 'PFC-1 current above nameplate', nameAr: 'تيار بنك المكثّفات ١ فوق اللوحة',
      tagCode: 'PFC-1.A', condition: 'GT', threshold: 36, severity: 'CRITICAL', delaySeconds: 60, hysteresis: 2 },
    { code: 'AL-PFC2-DEAD', name: 'PFC-2 drawing no current', nameAr: 'بنك المكثّفات ٢ لا يسحب تياراً',
      tagCode: 'PFC-2.A', condition: 'LT', threshold: 1, severity: 'CRITICAL', delaySeconds: 600 },
    { code: 'AL-CURE-TEMP', name: 'Cure zone temperature out of band', nameAr: 'حرارة منطقة المعالجة خارج النطاق',
      tagCode: 'DR-01.ZONE3', condition: 'LT', threshold: 92, severity: 'CRITICAL', delaySeconds: 60, hysteresis: 2 },
  ],
};
